version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
    ports:
      - "19001:19001"
    depends_on:
      - backend
  database:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    ports:
      - "9200:9200"
